# Generated by Django 6.0.1 on 2026-01-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='outlet',
            field=models.CharField(choices=[('CAFE', 'REC Cafe'), ('MART', 'REC Mart'), ('HUT', 'Hut Cafe')], max_length=20),
        ),
    ]
